name: Test
#Trigger for the workflow
  #Triggers only on push on master
on:
  pull_request:
    branches: [ "master" ]
      
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Prepare Maven
        run: mvn compile
      - name: Run System Tests
        run: mvn test