name: Run All Tests Before Merge
#Trigger for the workflow
  #Triggers only on push on master
on:
  pull_request:
    branches: [ "master" ]
      
jobs:
  call-workflow-all-tests:
    uses: ./.github/workflows/test.yaml
