name: Test on Push
on:
  push:
    branches:
      - Working

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn clean install

      - name: Publish test coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: target/site/jacoco/index.html

      - name: Publish PMD report
        uses: actions/upload-artifact@v2
        with:
          name: pmd-report
          path: target/site/pmd.html

      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: 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
          publish_dir: ./target/site/

